name: KittenWorldAuction
version: 1.0.0
main: ru.kittenworld.auction.AuctionPlugin
api-version: '1.21'
depend: [Vault]
softdepend: [Essentials]
commands:
  ah:
    description: Аукцион
    aliases: [auc, auction]
permissions:
  kittenworldauction.use:
    default: true
  kittenworldauction.admin:
    default: op
